[workspace]
members = [
    "src/yourcontrols/src-tauri",
    "src/yourcontrols-net",
    "src/yourcontrols-types",
    "src/yourcontrols-hoster",
    "src/yourcontrols-discord",
    "src/yourcontrols-gauge",
    "src/yourcontrols-definitions",
]

default-members = ["src/yourcontrols/src-tauri"]
